name: Java CI with Maven

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Find correct JAR
      id: find-jar
      run: |
        ls -lah target/
        output="$(find target/ -name "Alerter-*.jar" -type f -printf "%f\n" | grep -E '^Alerter-1.1-SNAPSHOT.jar$')"
        echo "::set-output name=jarname::$output"

    - name: Release the build
      if: ${{ github.event_name == 'push' }}
      uses: softprops/action-gh-release@v1
      with:
        files: target/${{ steps.find-jar.outputs.jarname }}
        body: ${{ join(github.event.commits.*.message, '\n') }}
        tag_name: ${{ github.ref_slug }}
        token: ${{ secrets.GITHUB_TOKEN }}
